"""
R.A.I. Operational Warning & Advisory Engine.
Evaluates model predictions, operational risk tiers, and atmospheric parameters
to synthesize actionable monitoring advisories while strictly distinguishing
model estimates from official government warnings.
"""
from typing import Dict, List, Any
import datetime

WARNING_LEVELS = {
    "LOW": "NO_WARNING",
    "MODERATE": "ADVISORY",
    "HIGH": "WATCH",
    "CRITICAL": "WARNING"
}

RECOMMENDED_ACTIONS = {
    "NO_WARNING": [
        "Normal operations. Standard weather monitoring.",
        "Verify routine agricultural irrigation schedules.",
        "Check daily forecast updates at standard intervals."
    ],
    "ADVISORY": [
        "Heightened convective monitoring advised.",
        "Inspect local drainage channels and storm water grates.",
        "Farmers: Postpone fertilizer or pesticide spraying pending cloudburst checks.",
        "Keep mobile devices charged and monitor R.A.I. radar updates."
    ],
    "WATCH": [
        "Potential heavy rainfall event (>=64.5 mm/24h) detected by R.A.I. ML pipeline.",
        "Farmers: Secure low-lying livestock and prepare crop field drainage bunds.",
        "Urban residents: Avoid low-lying underpasses and areas susceptible to waterlogging.",
        "Cross-reference live alerts on the official India Meteorological Department (IMD) portal."
    ],
    "WARNING": [
        "High-confidence severe rainfall event detected (Very Heavy / Extreme Rain Potential).",
        "Prepare emergency kits and secure essential supplies.",
        "Evacuate flood-prone basement structures and riparian agricultural zones.",
        "Follow official local disaster management authority (SDMA/NDMA) directives immediately."
    ]
}

def evaluate_warning(
    city: str,
    probability: float,
    risk_level: str,
    severity: str,
    horizon_hours: int,
    top_factors: List[Dict[str, Any]],
    model_version: str,
    timestamp: str = None
) -> Dict[str, Any]:
    """
    Synthesizes an operational warning package based on validated model predictions.
    """
    if timestamp is None:
        timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

    warning_level = WARNING_LEVELS.get(risk_level, "NO_WARNING")
    actions = RECOMMENDED_ACTIONS.get(warning_level, RECOMMENDED_ACTIONS["NO_WARNING"])

    top_feature_names = [f.get("featureName", f.get("feature", "")) for f in top_factors[:3]]
    drivers_text = ", ".join(top_feature_names) if top_feature_names else "Surface atmospheric parameters"

    summary_text = (
        f"R.A.I. Operational Warning Level: {warning_level} ({risk_level} Risk, {probability*100:.1f}% Probability) for {city}. "
        f"Key atmospheric drivers: {drivers_text}."
    )

    return {
        "warningLevel": warning_level,
        "operationalRisk": risk_level,
        "probability": probability,
        "horizonHours": horizon_hours,
        "severity": severity,
        "summary": summary_text,
        "recommendedActions": actions,
        "modelVersion": model_version,
        "timestamp": timestamp,
        "disclaimer": (
            "NOTICE: R.A.I. Model Warnings are predictive algorithmic estimates generated by calibrated machine learning models. "
            "They do not replace statutory disaster alerts issued by the India Meteorological Department (IMD) or State Disaster Management Authorities."
        )
    }
