/**
 * Location Context & Telemetry Coordinates for R.A.I.
 */

export interface UserLocation {
  readonly city: string;
  readonly region: string;
  readonly country: string;
  readonly lat: number;
  readonly lng: number;
  readonly formattedAddress: string;
}

/**
 * Sensibly curated popular quick-select locations covering major Indian metros,
 * state capitals, agro-industrial zones, and key international meteorological hubs.
 */
export const PRESET_CITIES: readonly UserLocation[] = [
  // Tier 1 Indian Metros & National Capital
  {
    city: 'Delhi',
    region: 'Delhi',
    country: 'India',
    lat: 28.6139,
    lng: 77.209,
    formattedAddress: 'New Delhi, Delhi NCR, India',
  },
  {
    city: 'Mumbai',
    region: 'Maharashtra',
    country: 'India',
    lat: 19.076,
    lng: 72.8777,
    formattedAddress: 'Mumbai, Maharashtra, India',
  },
  {
    city: 'Bengaluru',
    region: 'Karnataka',
    country: 'India',
    lat: 12.9716,
    lng: 77.5946,
    formattedAddress: 'Bengaluru, Karnataka, India',
  },
  {
    city: 'Ahmedabad',
    region: 'Gujarat',
    country: 'India',
    lat: 23.0225,
    lng: 72.5714,
    formattedAddress: 'Ahmedabad, Gujarat, India',
  },
  {
    city: 'Hyderabad',
    region: 'Telangana',
    country: 'India',
    lat: 17.385,
    lng: 78.4867,
    formattedAddress: 'Hyderabad, Telangana, India',
  },
  {
    city: 'Chennai',
    region: 'Tamil Nadu',
    country: 'India',
    lat: 13.0827,
    lng: 80.2707,
    formattedAddress: 'Chennai, Tamil Nadu, India',
  },
  {
    city: 'Kolkata',
    region: 'West Bengal',
    country: 'India',
    lat: 22.5726,
    lng: 88.3639,
    formattedAddress: 'Kolkata, West Bengal, India',
  },
  {
    city: 'Pune',
    region: 'Maharashtra',
    country: 'India',
    lat: 18.5204,
    lng: 73.8567,
    formattedAddress: 'Pune, Maharashtra, India',
  },

  // Major Indian State Capitals, Northern & Gangetic Plain Hubs
  {
    city: 'Lucknow',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 26.8467,
    lng: 80.9462,
    formattedAddress: 'Lucknow, Uttar Pradesh, India',
  },
  {
    city: 'Kanpur',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 26.4499,
    lng: 80.3319,
    formattedAddress: 'Kanpur, Uttar Pradesh, India',
  },
  {
    city: 'Varanasi',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 25.3176,
    lng: 82.9739,
    formattedAddress: 'Varanasi, Uttar Pradesh, India',
  },
  {
    city: 'Agra',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 27.1767,
    lng: 78.0081,
    formattedAddress: 'Agra, Uttar Pradesh, India',
  },
  {
    city: 'Prayagraj',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 25.4358,
    lng: 81.8463,
    formattedAddress: 'Prayagraj, Uttar Pradesh, India',
  },
  {
    city: 'Patna',
    region: 'Bihar',
    country: 'India',
    lat: 25.5941,
    lng: 85.1376,
    formattedAddress: 'Patna, Bihar, India',
  },
  {
    city: 'Jaipur',
    region: 'Rajasthan',
    country: 'India',
    lat: 26.9124,
    lng: 75.7873,
    formattedAddress: 'Jaipur, Rajasthan, India',
  },
  {
    city: 'Jodhpur',
    region: 'Rajasthan',
    country: 'India',
    lat: 26.2389,
    lng: 73.0243,
    formattedAddress: 'Jodhpur, Rajasthan, India',
  },
  {
    city: 'Udaipur',
    region: 'Rajasthan',
    country: 'India',
    lat: 24.5854,
    lng: 73.7125,
    formattedAddress: 'Udaipur, Rajasthan, India',
  },
  {
    city: 'Chandigarh',
    region: 'Chandigarh',
    country: 'India',
    lat: 30.7333,
    lng: 76.7794,
    formattedAddress: 'Chandigarh, India',
  },
  {
    city: 'Amritsar',
    region: 'Punjab',
    country: 'India',
    lat: 31.634,
    lng: 74.8723,
    formattedAddress: 'Amritsar, Punjab, India',
  },
  {
    city: 'Ludhiana',
    region: 'Punjab',
    country: 'India',
    lat: 30.901,
    lng: 75.8573,
    formattedAddress: 'Ludhiana, Punjab, India',
  },
  {
    city: 'Dehradun',
    region: 'Uttarakhand',
    country: 'India',
    lat: 30.3165,
    lng: 78.0322,
    formattedAddress: 'Dehradun, Uttarakhand, India',
  },
  {
    city: 'Shimla',
    region: 'Himachal Pradesh',
    country: 'India',
    lat: 31.1048,
    lng: 77.1734,
    formattedAddress: 'Shimla, Himachal Pradesh, India',
  },
  {
    city: 'Srinagar',
    region: 'Jammu & Kashmir',
    country: 'India',
    lat: 34.0837,
    lng: 74.7973,
    formattedAddress: 'Srinagar, Jammu & Kashmir, India',
  },

  // Western India (Gujarat & Maharashtra)
  {
    city: 'Surat',
    region: 'Gujarat',
    country: 'India',
    lat: 21.1702,
    lng: 72.8311,
    formattedAddress: 'Surat, Gujarat, India',
  },
  {
    city: 'Vadodara',
    region: 'Gujarat',
    country: 'India',
    lat: 22.3072,
    lng: 73.1812,
    formattedAddress: 'Vadodara, Gujarat, India',
  },
  {
    city: 'Gandhinagar',
    region: 'Gujarat',
    country: 'India',
    lat: 23.2156,
    lng: 72.6369,
    formattedAddress: 'Gandhinagar, Gujarat, India',
  },
  {
    city: 'Rajkot',
    region: 'Gujarat',
    country: 'India',
    lat: 22.3039,
    lng: 70.8022,
    formattedAddress: 'Rajkot, Gujarat, India',
  },
  {
    city: 'Bhavnagar',
    region: 'Gujarat',
    country: 'India',
    lat: 21.7645,
    lng: 72.1519,
    formattedAddress: 'Bhavnagar, Gujarat, India',
  },
  {
    city: 'Nagpur',
    region: 'Maharashtra',
    country: 'India',
    lat: 21.1458,
    lng: 79.0882,
    formattedAddress: 'Nagpur, Maharashtra, India',
  },
  {
    city: 'Nashik',
    region: 'Maharashtra',
    country: 'India',
    lat: 19.9975,
    lng: 73.7898,
    formattedAddress: 'Nashik, Maharashtra, India',
  },
  {
    city: 'Aurangabad',
    region: 'Maharashtra',
    country: 'India',
    lat: 19.8762,
    lng: 75.3433,
    formattedAddress: 'Chhatrapati Sambhajinagar (Aurangabad), Maharashtra, India',
  },

  // Central & Eastern India
  {
    city: 'Indore',
    region: 'Madhya Pradesh',
    country: 'India',
    lat: 22.7196,
    lng: 75.8577,
    formattedAddress: 'Indore, Madhya Pradesh, India',
  },
  {
    city: 'Bhopal',
    region: 'Madhya Pradesh',
    country: 'India',
    lat: 23.2599,
    lng: 77.4126,
    formattedAddress: 'Bhopal, Madhya Pradesh, India',
  },
  {
    city: 'Gwalior',
    region: 'Madhya Pradesh',
    country: 'India',
    lat: 26.2183,
    lng: 78.1828,
    formattedAddress: 'Gwalior, Madhya Pradesh, India',
  },
  {
    city: 'Jabalpur',
    region: 'Madhya Pradesh',
    country: 'India',
    lat: 23.1815,
    lng: 79.9864,
    formattedAddress: 'Jabalpur, Madhya Pradesh, India',
  },
  {
    city: 'Raipur',
    region: 'Chhattisgarh',
    country: 'India',
    lat: 21.2514,
    lng: 81.6296,
    formattedAddress: 'Raipur, Chhattisgarh, India',
  },
  {
    city: 'Ranchi',
    region: 'Jharkhand',
    country: 'India',
    lat: 23.3441,
    lng: 85.3096,
    formattedAddress: 'Ranchi, Jharkhand, India',
  },
  {
    city: 'Jamshedpur',
    region: 'Jharkhand',
    country: 'India',
    lat: 22.8046,
    lng: 86.2029,
    formattedAddress: 'Jamshedpur, Jharkhand, India',
  },
  {
    city: 'Bhubaneswar',
    region: 'Odisha',
    country: 'India',
    lat: 20.2961,
    lng: 85.8245,
    formattedAddress: 'Bhubaneswar, Odisha, India',
  },
  {
    city: 'Guwahati',
    region: 'Assam',
    country: 'India',
    lat: 26.1445,
    lng: 91.7362,
    formattedAddress: 'Guwahati, Assam, India',
  },

  // Southern India
  {
    city: 'Kochi',
    region: 'Kerala',
    country: 'India',
    lat: 9.9312,
    lng: 76.2673,
    formattedAddress: 'Kochi, Kerala, India',
  },
  {
    city: 'Thiruvananthapuram',
    region: 'Kerala',
    country: 'India',
    lat: 8.5241,
    lng: 76.9366,
    formattedAddress: 'Thiruvananthapuram, Kerala, India',
  },
  {
    city: 'Coimbatore',
    region: 'Tamil Nadu',
    country: 'India',
    lat: 11.0168,
    lng: 76.9558,
    formattedAddress: 'Coimbatore, Tamil Nadu, India',
  },
  {
    city: 'Madurai',
    region: 'Tamil Nadu',
    country: 'India',
    lat: 9.9252,
    lng: 78.1198,
    formattedAddress: 'Madurai, Tamil Nadu, India',
  },
  {
    city: 'Visakhapatnam',
    region: 'Andhra Pradesh',
    country: 'India',
    lat: 17.6868,
    lng: 83.2185,
    formattedAddress: 'Visakhapatnam, Andhra Pradesh, India',
  },
  {
    city: 'Vijayawada',
    region: 'Andhra Pradesh',
    country: 'India',
    lat: 16.5062,
    lng: 80.648,
    formattedAddress: 'Vijayawada, Andhra Pradesh, India',
  },
  {
    city: 'Mysore',
    region: 'Karnataka',
    country: 'India',
    lat: 12.2958,
    lng: 76.6394,
    formattedAddress: 'Mysore, Karnataka, India',
  },
  {
    city: 'Hubballi-Dharwad',
    region: 'Karnataka',
    country: 'India',
    lat: 15.3647,
    lng: 75.124,
    formattedAddress: 'Hubballi-Dharwad, Karnataka, India',
  },

  // Selected Key International Meteorological Hubs
  {
    city: 'London',
    region: 'England',
    country: 'United Kingdom',
    lat: 51.5074,
    lng: -0.1278,
    formattedAddress: 'London, England, United Kingdom',
  },
  {
    city: 'New York',
    region: 'New York',
    country: 'United States',
    lat: 40.7128,
    lng: -74.006,
    formattedAddress: 'New York, NY, United States',
  },
  {
    city: 'Tokyo',
    region: 'Kanto',
    country: 'Japan',
    lat: 35.6762,
    lng: 139.6503,
    formattedAddress: 'Tokyo, Japan',
  },
  {
    city: 'Dubai',
    region: 'Dubai',
    country: 'United Arab Emirates',
    lat: 25.2048,
    lng: 55.2708,
    formattedAddress: 'Dubai, United Arab Emirates',
  },
  {
    city: 'Singapore',
    region: 'Central',
    country: 'Singapore',
    lat: 1.3521,
    lng: 103.8198,
    formattedAddress: 'Singapore, Singapore',
  },
  {
    city: 'Sydney',
    region: 'New South Wales',
    country: 'Australia',
    lat: -33.8688,
    lng: 151.2093,
    formattedAddress: 'Sydney, New South Wales, Australia',
  },
  {
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    lat: 48.8566,
    lng: 2.3522,
    formattedAddress: 'Paris, Île-de-France, France',
  },
] as const;

export const DEFAULT_USER_LOCATION: UserLocation = PRESET_CITIES[0]!;

export const findCityByName = (cityName: string): UserLocation | undefined => {
  const normalized = cityName.trim().toLowerCase();
  return PRESET_CITIES.find(
    (c) => c.city.toLowerCase() === normalized || c.formattedAddress.toLowerCase().includes(normalized)
  );
};
